camera:
    fx: 609.799499511719
    fy: 609.5458984375
    dims: [480, 640]
segmentation:
    dia: .05715
    radius_min_size: .01
    lower_bound: [150, 60, 80]
    upper_bound: [256, 100, 170]
subscribers:
    rgb: "~rgb"
    depth: "~depth"
publishers:
    pose: "~pose"
    mask: "~mask"